source 'https://rubygems.org'
ruby "2.3.0"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.0'
# Use sqlite3 as the database for Active Record

gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

group :development, :test do
  gem 'govuk_frontend_toolkit', :git => "https://github.com/alphagov/govuk_frontend_toolkit_gem.git", :submodules => true
  gem 'jasmine-rails'
  gem 'phantomjs'
  gem 'rubocop'
  gem 'brakeman'
  gem 'rspec-rails'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'factory_girl_rails'
  gem 'annotate'
  gem 'capybara'
  gem 'capybara-select2'
  gem 'better_errors'
  gem 'selenium'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'faker'
  gem 'database_cleaner'
  gem 'rspec_junit_formatter'
  gem 'rack-mini-profiler'
end

